name: Build & Publish NuGet Package

on:
  push:
    branches:
      - main # Run on all pushes to main
    tags:
      - "v*.*.*" # Publish only on version tags
    paths-ignore:
      - '**.md'
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkgs

      - name: Push package to NuGet
        if: startsWith(github.ref, 'refs/tags/v') # <-- Only publish on version tags
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.LITEMEDIATOR_API_KEY }} --source https://api.nuget.org/v3/index.json
