name: Build & Publish NuGet Package

on:
  push:
    tags:
      - "v*.*.*" # Only publish on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --no-build --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkgs

      - name: Push package to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.LiteMediator_API_KEY }} --source https://api.nuget.org/v3/index.json
